apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-monolithic
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flaskapp-monolithic
        image: team333/monolithic-code:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      volumes:
      - name: ca-certs
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-monolithic
  labels:
    app: flask
spec:
  ports:
  - port: 8000
    protocol: TCP
    name: flask
    targetPort: 8000
  selector:
    app: flask
  type: ClusterIP
